server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-status-check
          uri: lb://demo-resource-server
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: albums
          uri: lb://demo-albums-service
          predicates:
            - Path=/albums
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: photos
          uri: lb://demo-photo-service
          predicates:
            - Path=/photos
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie