server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: user-status-check
          uri: http://localhost:8081
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie